name: password_vault
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Flutter essentials
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter 
  
  # UI Theme and Style related packages
  cupertino_icons: ^1.0.6
  flutter_svg: ^1.1.6 
  flutter_easyloading: ^3.0.5 
  flutter_slidable: ^2.0.0
  
  # Testing and debugging related packages
  device_preview: ^1.1.0  ## Remove this in production
  test: ^1.24.0
  mocktail: ^1.0.0
  
  # State management and data handling packages
  flutter_riverpod: ^2.1.3 
  http: ^1.2.1
  dart_jsonwebtoken: ^2.13.0
  hive: ^2.2.3 
  hive_flutter: ^1.1.0 
  go_router: ^11.1.4 

  # System and device related packages
  permission_handler: ^10.2.0
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.0.14
   
  # Utility packages
  camera: ^0.10.5+9 
  image_picker: ^0.8.7+3 
  file_picker: ^5.3.1
  photo_view: ^0.14.0 
  styled_text: ^8.1.0
  uuid: ^3.0.7 
  pdf: ^3.10.4
  url_launcher: ^6.1.14
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
